mongo:
    image: mongo:3.0.6
    expose:
        - "27017"
qotd:
    image: quoteoftheday:latest
    command:
      -Dhttp.port=8081
      -Dplay.crypto.secret=abcdefghijk
    expose:
      - "8081"
    ports:
      - "8081:8081"
    links:
        - mongo
yln:
    image: yln:latest
    expose:
          - "8080"
    ports:
      - "8080:8080"
yksbt:
    image: "1science/sbt:latest"
    entrypoint: "sbt test"
    command:
        -Dqotd.url=http://qotd:8081/quote
        -Dyln.url=http://yln:8080/number
    volumes:
        - "$PWD/:/app:rw"
        - "$HOME/.m2:/root/.m2:rw"
        - "$HOME/.ivy2:/root/.ivy2:rw"
    links:
        - qotd
        - yln
    stdin_open: true